[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.44.2", features = ["net", "io-util", "rt-multi-thread", "macros", "time"] }
tokio-graceful-shutdown = "0.16.0"
url = "2.5.4"

